<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <RootNamespace>HoleElevation</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <Configurations>Debug;R2022;R2021;R2020</Configurations>
    <CodeAnalysisRuleSet>..\stylecop.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64;AnyCPU</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'R2022' ">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'R2021' ">
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'R2020' or '$(Configuration)'=='Debug'">
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)'=='R2020' or '$(Configuration)'=='Debug'">
    <PackageReference Include="Autodesk.Revit.SDK" Version="2020.2.1" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='R2021'">
    <PackageReference Include="Autodesk.Revit.SDK" Version="2021.0.0" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='R2022'">
    <PackageReference Include="Autodesk.Revit.SDK" Version="2022.0.2.392" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="2.29.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GENPRO_Design\GENPRO_Design.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <PackageGuid>89f46c75-b999-4a28-bb63-dc776b2a3170</PackageGuid>
    <UpgradeCode>1d963d0a-0203-4acb-9745-19ddf7026880</UpgradeCode>
    <Command__HoleElevation_Cmd>0f27c78b-02b6-450a-9233-8e8a4f9fce26</Command__HoleElevation_Cmd>
  </PropertyGroup>
</Project>