{
  "format": 1,
  "restore": {
    "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\HoleElevation\\HoleElevation.csproj": {}
  },
  "projects": {
    "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\GENPRO_Design\\GENPRO_Design.csproj": {
      "restore": {
        "projectUniqueName": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\GENPRO_Design\\GENPRO_Design.csproj",
        "projectName": "GENPRO_Design",
        "projectPath": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\GENPRO_Design\\GENPRO_Design.csproj",
        "frameworks": {
          "net472": {
            "projectReferences": {}
          }
        }
      },
      "frameworks": {
        "net472": {}
      }
    },
    "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\HoleElevation\\HoleElevation.csproj": {
      "version": "1.0.0",
      "restore": {
        "projectUniqueName": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\HoleElevation\\HoleElevation.csproj",
        "projectName": "HoleElevation",
        "projectPath": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\HoleElevation\\HoleElevation.csproj",
        "packagesPath": "C:\\Users\\Undea\\.nuget\\packages\\",
        "outputPath": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\HoleElevation\\obj\\",
        "projectStyle": "PackageReference",
        "fallbackFolders": [
          "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder"
        ],
        "configFilePaths": [
          "C:\\Users\\Undea\\AppData\\Roaming\\NuGet\\NuGet.Config",
          "C:\\Program Files (x86)\\NuGet\\Config\\Microsoft.VisualStudio.Offline.config"
        ],
        "originalTargetFrameworks": [
          "net472"
        ],
        "sources": {
          "C:\\Program Files (x86)\\Microsoft SDKs\\NuGetPackages\\": {},
          "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\locaNugets": {},
          "https://api.nuget.org/v3/index.json": {}
        },
        "frameworks": {
          "net472": {
            "targetAlias": "net472",
            "projectReferences": {
              "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\GENPRO_Design\\GENPRO_Design.csproj": {
                "projectPath": "C:\\Users\\Undea\\OneDrive\\Рабочий стол\\WorkProjects\\HoleElevation\\HoleElevation\\GENPRO_Design\\GENPRO_Design.csproj"
              }
            }
          }
        },
        "warningProperties": {
          "warnAsError": [
            "NU1605"
          ]
        }
      },
      "frameworks": {
        "net472": {
          "targetAlias": "net472",
          "dependencies": {
            "Autodesk.Revit.SDK": {
              "include": "Compile, Build, Native, ContentFiles, Analyzers, BuildTransitive",
              "target": "Package",
              "version": "[2020.2.1, )"
            },
            "CSharpFunctionalExtensions": {
              "target": "Package",
              "version": "[2.29.0, )"
            },
            "MvvmLight": {
              "target": "Package",
              "version": "[5.4.1.1, )"
            },
            "StyleCop.Analyzers": {
              "include": "Runtime, Build, Native, ContentFiles, Analyzers, BuildTransitive",
              "suppressParent": "All",
              "target": "Package",
              "version": "[1.1.118, )"
            }
          },
          "runtimeIdentifierGraphPath": "C:\\Program Files\\dotnet\\sdk\\6.0.202\\RuntimeIdentifierGraph.json"
        }
      }
    }
  }
}